Tickets/dm 34594
lsst-dm/dm_dev_guide pull request #524
Opened 2022-04-28 19:55 UTC by womullan

start focus times

2022-04-28 20:15 UTC, isullivan commented on team/focus-times.rst
> +- September 18-22
September 19-23?

2022-04-28 20:16 UTC, ktlim commented on communications/slack-culture.rst
>  Focus Friday
Adjust this heading too.

2022-04-29 22:38 UTC, frossie requested changes
So I obviously don't mind, but I think we had conceived of the "meeting holidays" to not be under Focus Friday rules, and instead (1) cancel all standing meetings (2) highlight to staff that it's a good time to take time off without "falling behind". This was quite a lot laxer than Focus Friday rules. We should probably have a wider discussion to make sure we agree on the specifics?

2022-05-01 19:48 UTC, womullan commented
ok on agenda for the morning

2022-05-02 21:02 UTC, closed without merging